-- Fit-Zone Gym initial schema. Runs inside the gym_app schema (Flyway sets search_path).
-- Types are chosen to match Hibernate 6 / PostgreSQL defaults so ddl-auto=validate passes.

CREATE TABLE users (
    id          uuid PRIMARY KEY,
    name        varchar(255)             NOT NULL,
    email       varchar(255)             NOT NULL,
    phone       varchar(255),
    address     varchar(255),
    age         integer,
    role        varchar(16)              NOT NULL DEFAULT 'USER',
    google_sub  varchar(255),
    created_at  timestamp with time zone NOT NULL,
    updated_at  timestamp with time zone NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_google_sub UNIQUE (google_sub),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE plans (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255)             NOT NULL,
    price_minor     bigint                   NOT NULL,
    duration_months integer                  NOT NULL,
    features        jsonb                    NOT NULL DEFAULT '[]'::jsonb,
    popular         boolean                  NOT NULL DEFAULT false,
    active          boolean                  NOT NULL DEFAULT true,
    sort_order      integer                  NOT NULL DEFAULT 0,
    created_at      timestamp with time zone NOT NULL,
    updated_at      timestamp with time zone NOT NULL
);

CREATE TABLE memberships (
    id          uuid PRIMARY KEY,
    user_id     uuid                     NOT NULL,
    plan_id     bigint,
    plan_name   varchar(255)             NOT NULL,
    price_minor bigint                   NOT NULL,
    start_date  date                     NOT NULL,
    end_date    date                     NOT NULL,
    status      varchar(16)              NOT NULL DEFAULT 'ACTIVE',
    created_at  timestamp with time zone NOT NULL,
    CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_memberships_plan FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE SET NULL,
    CONSTRAINT chk_memberships_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED'))
);

CREATE TABLE payments (
    id                  uuid PRIMARY KEY,
    membership_id       uuid                     NOT NULL,
    user_id             uuid                     NOT NULL,
    amount_minor        bigint                   NOT NULL,
    status              varchar(16)              NOT NULL DEFAULT 'PENDING',
    method              varchar(255),
    provider_payment_id varchar(255),
    created_at          timestamp with time zone NOT NULL,
    CONSTRAINT fk_payments_membership FOREIGN KEY (membership_id) REFERENCES memberships (id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_payments_provider_payment_id UNIQUE (provider_payment_id),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED'))
);

CREATE TABLE contact_submissions (
    id         uuid PRIMARY KEY,
    name       varchar(255)             NOT NULL,
    email      varchar(255)             NOT NULL,
    message    text                     NOT NULL,
    status     varchar(16)              NOT NULL DEFAULT 'NEW',
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT chk_contact_status CHECK (status IN ('NEW', 'READ', 'ARCHIVED'))
);

CREATE TABLE admin_allowlist (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      varchar(255)             NOT NULL,
    added_by   varchar(255),
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT uq_admin_allowlist_email UNIQUE (email)
);

CREATE INDEX idx_memberships_user_id ON memberships (user_id);
CREATE INDEX idx_memberships_plan_id ON memberships (plan_id);
CREATE INDEX idx_memberships_status ON memberships (status);
CREATE INDEX idx_payments_membership_id ON payments (membership_id);
CREATE INDEX idx_payments_user_id ON payments (user_id);
CREATE INDEX idx_payments_status ON payments (status);
CREATE INDEX idx_contact_status ON contact_submissions (status);
